### PR TITLE
feat: remove other props in actions type inference

### PR DESCRIPTION
**Pull request by stkevintan**
fix type inference problem:
image

### CODE REVIEW

**Comment by Runjuu** [comment]
Seems there has some type issues when run `yarn run lint`

image

**Comment by stkevintan** [comment]
@Runjuu I think I just encounter a ts 3.4.x bug, related issue: https://github.com/ksxnodemodules/typescript-tuple/issues/8

It only affect lint, but not in the IDE or compile, I have no clue to fix it by now.....

**Comment by stkevintan** [comment]
@Runjuu  I finally figure out how to solve the annoying typescript 3.4+ recursive types error. please review the updated code.

图片

**Comment by Runjuu** [comment]
@stkevintan Nice work! 🍻Thanks

**Pull request merged**
